Update Classes for UTF8 Issues
Prior to this commit on puppet enteprise v3 and ruby 1.9 the content attribute
would fail due to munge having an issue with the UTF8 and binary

```puppet
Error: Failed to apply catalog: Parameter content failed on File[cloud1_euca.p12]: Munging failed for value
...
class content: invalid byte sequence in UTF-8
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/checksums.rb:15:in `checksum?'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type/file/content.rb:50:in `block (2 levels) in <module:Puppet>'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/parameter.rb:420:in `munge'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/property.rb:433:in `munge'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/property.rb:564:in `block in should='
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/property.rb:564:in `collect'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/property.rb:564:in `should='
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type/file/content.rb:134:in `should='
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/property.rb:615:in `value='
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:656:in `[]='
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:2248:in `block in set_parameters'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:2242:in `each'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:2242:in `set_parameters'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:2198:in `initialize'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type/file.rb:409:in `initialize'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:288:in `new'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:288:in `to_ral'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:572:in `block in to_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:553:in `each'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:553:in `to_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:477:in `to_ral'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:82:in `convert_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:77:in `retrieve_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:107:in `prepare_and_retrieve_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:159:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:45:in `block (5 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent/locker.rb:20:in `lock'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:45:in `block (4 levels) in run'
/opt/puppet/lib/ruby/1.9.1/sync.rb:227:in `sync_synchronize'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:45:in `block (3 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:119:in `with_client'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:42:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:84:in `run_in_fork'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:41:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `call'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `controlled_run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:39:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:353:in `onetime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:327:in `run_command'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:364:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:456:in `plugin_hook'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:364:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:504:in `exit_on_fail'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:364:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:132:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:86:in `execute'
/opt/puppet/bin/puppet:4:in `<main>'
Error: Could not send report: Error 400 on SERVER: (<unknown>): did not find expected <document start> at line 1 column 1
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/rest.rb:185:in `is_http_200?'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/rest.rb:153:in `save'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/indirection.rb:279:in `save'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:200:in `send_report'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:194:in `ensure in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:194:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:45:in `block (5 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent/locker.rb:20:in `lock'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:45:in `block (4 levels) in run'
/opt/puppet/lib/ruby/1.9.1/sync.rb:227:in `sync_synchronize'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:45:in `block (3 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:119:in `with_client'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:42:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:84:in `run_in_fork'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:41:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `call'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `controlled_run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:39:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:353:in `onetime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:327:in `run_command'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:364:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:456:in `plugin_hook'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:364:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:504:in `exit_on_fail'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:364:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:132:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:86:in `execute'
```